---
name: "convert"
version: "0.6.2"
usage: "convert"
description: |-
  Convert Helm charts into Kustomize compatible package
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/helm-convert"
hooks:
  install: "$HELM_PLUGIN_DIR/install.sh"
